# This workflow generates test result and code coverage reports.
name: Generate code reports

on:
  workflow_run:
    workflows:
      - Run tests and code checks
    types:
      - completed

permissions:
  # Required by actions/checkout
  contents: read
  # Required by mikepenz/action-junit-report
  checks: write
  # Required by mi-kas/kover-report
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download test report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: |
            **/build/test-results/test/TEST-*.xml

      - name: Create coverage report
        if: ${{ github.event.pull_request }}
        run: ./gradlew koverXmlReport

      - name: Post coverage report as comment
        if: ${{ github.event.pull_request }}
        uses: mi-kas/kover-report@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            ${{ github.workspace }}/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
